# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Matthew Apuya
description: Matthew Apuya's Official Website
baseurl: ""
url: "https://matthewapuya.com"

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Matthew Apuya
  description:
    - technical services engineer
    - prev. swe & product
    - computer science @ nyu
    - digital creator
    - the one piece is real
  resume: assets/resume.pdf
  address:
    - New York, NY
  contact:
    # phone: +1 234 567 890
    email: hello@matthewapuya.com
  profiles:
    github: https://github.com/mapuya19
    # instagram: https://www.instagram.com/matthewapuya
    linkedin: https://www.linkedin.com/in/matthewapuya
    photography: https://apuya.univer.se/
    # youtube: https://youtube.com/@apuya

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
